[jOOQ/jOOQ#11960] Prevent NoClassDefFoundError
The previous implementation required Redshift users to also have the pgjdbc driver on the classpath to prevent NoClassDefFoundError, but that should not be necessary.